#!/usr/bin/env python3
"""Generate a deterministic mock database for dashboard screenshots.

The README's screenshots must never contain real requests, account data, or
credentials. This builds a fixed, reproducible dataset instead, so a screenshot
can be regenerated byte-for-byte after a UI change rather than being
hand-captured from whatever an instance happened to hold.

Usage:
    python3 scripts/make-mock-data.py [output-dir]

It writes the SQLite file and a config.json pointing at it, then prints the
command to run. The data is entirely synthetic: model names are real (they come
from the platforms' published tables) but every request, token count and cost is
invented by a seeded generator.

Every request row is reproducible byte-for-byte; only the `created_at` column
defaults to wall-clock time, which nothing in the dashboard reads. Pass --today
to anchor the range to the real current date (what you want when the date axis
should look current) or omit it for a fixed range.
"""

import argparse
import datetime
import json
import os
import random
import sqlite3
import sys

# A fixed seed: the same generator state on every run, so a regenerated mock
# differs only where the schema or the generator changed.
SEED = 20260922

# Synthetic identities. Only the platform set and model names are real, so the
# panels group and label the way a live instance does; the volumes are invented.
PLATFORMS = {
    "opencode-go": {
        "weight": 58,
        "tps": 46,
        "models": [
            ("glm-5.2", "complex"),
            ("glm-5.1", "think"),
            ("kimi-k3", "default"),
            ("kimi-k2.7-code", "complex"),
            ("kimi-k2.6", "default"),
            ("qwen3.7-plus", "fast"),
            ("qwen3.7-max", "background"),
            ("qwen3.6-plus", "fast"),
            ("qwen3.5-plus", "background"),
            ("mimo-v2", "think"),
            ("deepseek-v4-flash", "default"),
            ("deepseek-v4-pro", "think"),
        ],
    },
    "commandcode": {
        "weight": 26,
        "tps": 19,
        "models": [
            ("deepseek/deepseek-v4.1-flash", "default"),
            ("deepseek/deepseek-v4-pro", "think"),
            ("moonshotai/Kimi-K2.6", "default"),
            ("deepseek/deepseek-v4-flash", "fast"),
        ],
    },
    "cline-pass": {
        "weight": 16,
        "tps": 62,
        "models": [
            ("cline-pass/deepseek-v4.1-flash", "default"),
            ("cline-pass/deepseek-v4-pro", "think"),
            ("grok-4-fast", "fast"),
        ],
    },
}

# The platforms that bill a peak rate for the deepseek families, and the window
# they bill it in (weekday UTC 01-04 and 06-10, matching history.peakSchedules).
# Generating rows inside and outside the window keeps the History tab's Peak
# badge present in every screenshot.
#
# Per platform, like the backend table: each platform covers the models its own
# pricing table gives a peak column, and ClinePass's set is narrower. Both Flash
# spellings are listed for it because its table names the row "DeepSeek V4
# Flash" while its roster serves deepseek-v4.1-flash.
PEAK_FAMILIES = {"deepseek-v4.1-flash", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "deepseek-v4-pro"}
CLINE_PEAK_FAMILIES = {"deepseek-v4.1-flash", "deepseek-v4-flash", "deepseek-v4-pro"}

# excludes_holidays mirrors peakSchedule.excludesHolidays: OpenCode Go and
# ClinePass inherit DeepSeek's exemption, CommandCode states its own rule
# without one. Getting this wrong here is invisible in a way the Go table's
# equivalent is not - it would put a Peak badge on a holiday row in the README
# screenshot, where the backend prices that row off-peak.
PEAK_COVERAGE = {
    "opencode-go": (PEAK_FAMILIES, True),
    "commandcode": (PEAK_FAMILIES, False),
    "cline-pass": (CLINE_PEAK_FAMILIES, True),
}
PEAK_WINDOWS = ((1, 4), (6, 10))


def load_holidays() -> set:
    """Chinese public holidays, read from the seed baked into the binary.

    Reusing the shipped seed rather than the network keeps this generator
    offline and keeps the two in step: a mock showing a badge the binary would
    not is the one failure this function exists to prevent.
    """
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "internal", "history", "seed_holidays_cn.json")
    with open(path, encoding="utf-8") as handle:
        return {d["date"] for d in json.load(handle)["days"] if d["isOffDay"]}


HOLIDAYS = load_holidays()


def peak_multiplier(provider: str, model: str, when: datetime.datetime) -> float:
    entry = PEAK_COVERAGE.get(provider)
    if not entry:
        return 1.0
    covered, excludes_holidays = entry
    if model.split("/")[-1] not in covered:
        return 1.0
    if when.weekday() >= 5:  # Saturday/Sunday are off-peak
        return 1.0
    if excludes_holidays and when.date().isoformat() in HOLIDAYS:
        return 1.0
    return 2.0 if any(lo <= when.hour < hi for lo, hi in PEAK_WINDOWS) else 1.0


def build_requests(rng: random.Random, days: int, today: datetime.date, now_utc: datetime.datetime):
    """Yield one dict per synthetic request across the last `days` days."""
    platforms = [(p, cfg["weight"]) for p, cfg in PLATFORMS.items()]
    names = [p for p, _ in platforms]
    weights = [w for _, w in platforms]

    for offset in range(days - 1, -1, -1):
        day = today - datetime.timedelta(days=offset)
        # Weekends are quieter; a few days carry no traffic at all, which
        # exercises the empty-column path the daily chart draws.
        if day.weekday() >= 5:
            volume = rng.randint(3, 12)
        else:
            volume = rng.randint(18, 46)
        if offset in (11, 19):
            volume = 0

        for _ in range(volume):
            provider = rng.choices(names, weights=weights, k=1)[0]
            model, scenario = rng.choice(PLATFORMS[provider]["models"])
            # A long tail of small requests with a few large ones, so the token
            # and cost distributions have a realistic shape rather than a flat
            # one.
            big = rng.random() < 0.12
            output = rng.randint(3000, 14000) if big else rng.randint(120, 2600)
            inp = rng.randint(4000, 60000) if big else rng.randint(180, 9000)
            cache_read = rng.randint(20000, 180000) if big else rng.randint(0, 24000)
            cache_create = rng.randint(2000, 22000) if rng.random() < 0.35 else 0

            # The anchor day is capped at the current UTC time so no row is dated
            # in the future. The History column phrases recent stamps relatively,
            # and a row reading "12 hours from now" is a data bug that reads as a
            # rendering one - it is the first thing anyone notices in a
            # screenshot. Capping the hour alone is not enough: the generated
            # minute can still land past the current one.
            last_hour = now_utc.hour if day == today else 23
            hour = rng.randint(0, max(0, last_hour))
            minute, second = rng.randint(0, 59), rng.randint(0, 59)
            if day == today and hour == now_utc.hour:
                # Same hour: stay inside the elapsed part of it.
                minute = rng.randint(0, max(0, now_utc.minute))
                if minute == now_utc.minute:
                    second = rng.randint(0, max(0, now_utc.second))
            when = datetime.datetime(
                day.year, day.month, day.day, hour, minute, second,
                tzinfo=datetime.timezone.utc,
            )
            mult = peak_multiplier(provider, model, when)

            # Whole-request duration: the generation phase plus a first-token
            # allowance, which is why measured throughput lands a little under
            # the platform's raw rate.
            tps = PLATFORMS[provider]["tps"] * rng.uniform(0.75, 1.25)
            duration_ms = int(output / tps * 1000 + rng.uniform(500, 2500))

            # A failure rate per platform, so the success column is not a wall
            # of 100% and the health rows have range.
            success = 0 if rng.random() < 0.06 else 1
            cost = (inp * 0.4 + output * 1.6 + cache_read * 0.04 + cache_create * 0.5) / 1e6 * mult

            yield {
                "model": model,
                "provider": provider,
                "scenario": scenario,
                "start_time": when.strftime("%Y-%m-%dT%H:%M:%S.") + f"{when.microsecond // 1000:03d}Z",
                "duration_ms": duration_ms,
                "input_tokens": inp,
                "output_tokens": output,
                "cache_read_tokens": cache_read,
                "cache_creation_tokens": cache_create,
                "cost_usd": round(cost, 8),
                "success": success,
                "streaming": 1 if rng.random() < 0.9 else 0,
                "attempt": rng.choices([1, 2, 3], weights=[92, 6, 2], k=1)[0],
                "error_msg": None if success else "upstream returned 503",
                "peak_multiplier": mult,
                "requested_model": None,
            }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("out_dir", nargs="?", default=".tmp/mock")
    parser.add_argument("--days", type=int, default=30)
    parser.add_argument("--today", action="store_true",
                        help="anchor the range to the real current date instead of a fixed one")
    args = parser.parse_args()

    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)
    db_path = os.path.join(out_dir, "data.db")
    if os.path.exists(db_path):
        os.remove(db_path)
    for suffix in ("-wal", "-shm"):
        if os.path.exists(db_path + suffix):
            os.remove(db_path + suffix)

    anchor = datetime.date.today() if args.today else datetime.date(2026, 9, 22)
    rng = random.Random(SEED)

    db = sqlite3.connect(db_path)
    db.executescript("""
        CREATE TABLE requests (
            id TEXT PRIMARY KEY, model TEXT NOT NULL, requested_model TEXT, provider TEXT, scenario TEXT,
            start_time TIMESTAMP NOT NULL, duration_ms INTEGER,
            input_tokens INTEGER, output_tokens INTEGER,
            cache_read_tokens INTEGER DEFAULT 0, cache_creation_tokens INTEGER DEFAULT 0,
            cost_usd REAL, cost_source TEXT, details_known INTEGER NOT NULL DEFAULT 1,
            usage_trusted INTEGER NOT NULL DEFAULT 0, streaming INTEGER, success INTEGER,
            error_msg TEXT, attempt INTEGER DEFAULT 1,
            peak_multiplier REAL NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX idx_requests_start_time ON requests(start_time);
    """)

    # Only the anchor day can contain the future, and only when it is today;
    # the fixed anchor is in the past and is unaffected.
    now_utc = datetime.datetime.now(datetime.timezone.utc)
    rows = list(build_requests(rng, args.days, anchor, now_utc))
    # A handful of rows the importer would write: usage known, timing never
    # observed locally. These are what exercise the "unknown throughput" path.
    for i in range(6):
        rows.append({
            "model": "glm-5.2", "provider": "opencode-go", "scenario": "default",
            "start_time": (anchor - datetime.timedelta(days=i)).strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "duration_ms": 0, "input_tokens": 2400, "output_tokens": 1800,
            "cache_read_tokens": 0, "cache_creation_tokens": 0,
            "cost_usd": 0.0042, "success": 1, "streaming": 1, "attempt": 1,
            "error_msg": None, "peak_multiplier": 1.0, "requested_model": None,
            # details_known = 0 marks a row with no locally observed timing.
            "_details_known": 0,
        })

    # A few rerouted requests, so the History tab's requested-vs-served pair is
    # present in the screenshots rather than a column that always reads empty.
    for i, (requested, served, provider) in enumerate([
        ("claude-sonnet-4-5", "glm-5.2", "opencode-go"),
        ("claude-opus-4-1", "kimi-k3", "opencode-go"),
        ("claude-haiku-4-5", "qwen3.7-plus", "opencode-go"),
    ]):
        when = anchor - datetime.timedelta(days=i, hours=1)
        rows.append({
            "model": served, "requested_model": requested, "provider": provider,
            "scenario": "override",
            "start_time": when.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "duration_ms": 5200 + i * 900, "input_tokens": 5200 + i * 400,
            "output_tokens": 1400 + i * 200, "cache_read_tokens": 18000, "cache_creation_tokens": 0,
            "cost_usd": 0.0126, "success": 1, "streaming": 1, "attempt": 1,
            "error_msg": None, "peak_multiplier": 1.0,
        })

    for index, row in enumerate(rows):
        details_known = row.pop("_details_known", 1)
        db.execute("""
            INSERT OR REPLACE INTO requests
              (id, model, requested_model, provider, scenario, start_time, duration_ms,
               input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens,
               cost_usd, cost_source, details_known, usage_trusted, streaming, success,
               error_msg, attempt, peak_multiplier)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?)
        """, (
            f"mock-{index:05d}", row["model"], row["requested_model"], row["provider"], row["scenario"],
            row["start_time"], row["duration_ms"], row["input_tokens"], row["output_tokens"],
            row["cache_read_tokens"], row["cache_creation_tokens"], row["cost_usd"], "estimated",
            details_known, row["streaming"], row["success"], row["error_msg"], row["attempt"],
            row["peak_multiplier"],
        ))
    db.commit()

    total = db.execute("SELECT COUNT(*) FROM requests").fetchone()[0]
    span = db.execute("SELECT MIN(start_time), MAX(start_time) FROM requests").fetchone()
    db.close()

    config_path = os.path.join(out_dir, "config.json")
    with open(config_path, "w") as handle:
        json.dump({
            "api_key": "mock-local-key",
            "host": "127.0.0.1",
            "port": 3456,
            "hot_reload": False,
            "catalog": {"enabled": False},
            "storage": {"database_path": db_path, "retention_days": 90, "wal_enabled": True},
        }, handle, indent=2)

    print(f"wrote {total} synthetic requests to {db_path}")
    print(f"  range: {span[0]} .. {span[1]}")
    print(f"  config: {config_path}")
    print()
    print("Run the dashboard against it with:")
    print(f"  ./bin/routatic-proxy start --config {config_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
