#!/usr/bin/env python3
"""Regenerate internal/history/seed_holidays_cn.json.

The peak rule exempts Chinese public holidays, and the calendar is not
published as an API - it is announced once a year as a State Council notice and
republished as data by third parties. `internal/history/holidays.go` fetches
NateScarlet/holiday-cn at runtime; this script bakes the same source into the
binary so the first requests after a cold start, and every request if the fetch
never succeeds, are priced against a real calendar instead of an empty one.

The seed is written in the upstream file's own shape (a `days` array of
{name, date, isOffDay}) so one parser reads both the seed and a live payload.

Usage:
    python3 scripts/make-holiday-seed.py
"""

import json
import urllib.request

YEARS = range(2007, 2027)
SOURCE = "https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/{}.json"
OUT = "internal/history/seed_holidays_cn.json"


def main() -> int:
    days = []
    for year in YEARS:
        try:
            with urllib.request.urlopen(SOURCE.format(year), timeout=30) as resp:
                payload = json.load(resp)
        except Exception as err:  # a missing year is a gap in the seed, so stop
            raise SystemExit(f"{year}: {err}")
        if not payload.get("days"):
            raise SystemExit(f"{year}: source returned no days")
        days.extend(payload["days"])

    # Only the off days matter; the upstream `isOffDay: false` rows are 调休
    # make-up workdays. They are dropped here rather than at parse time so the
    # file states the same thing the parser reads, and the count below is the
    # number that actually governs billing.
    off = [d for d in days if d["isOffDay"]]
    body = {
        "_comment": (
            "Chinese public holidays, generated by scripts/make-holiday-seed.py from "
            "NateScarlet/holiday-cn, which scrapes the State Council notice daily. Same "
            "shape as the upstream per-year file so one parser reads both. Only isOffDay "
            "rows are kept: the others are make-up workdays, which cannot change a peak "
            "verdict (see peakSchedule.excludesHolidays). Regenerate once the next year's "
            "notice is published."
        ),
        "days": off,
    }
    with open(OUT, "w", encoding="utf-8") as handle:
        json.dump(body, handle, ensure_ascii=False, indent=1, sort_keys=True)
        handle.write("\n")

    years = sorted({d["date"][:4] for d in off})
    print(f"wrote {len(off)} holidays across {years[0]}..{years[-1]} to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
